In [ ]:
# find sign of x
x = input("Enter x: ")
print("value of x:", x)
print(type(x))


value of x: 23
<class 'str'>


In [ ]:
# converting string x to int x
x = int(x)
# check sgin 
if x> 0:
    print("x is positive")
elif x<0:
    print("x is negative")
else:
    print("x is zero")

x is positive


In [ ]:
# assignment
x =5
 
# multipule assignments
a,b,c=1, "ok",3

#arithmetic operators
x =10
y =3
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x//y)
print(x**y)

# assignments opratores 
x*=5
print(x)
x-=50
print(x)

# comparison operators 
print(x== y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)

13
7
30
3.3333333333333335
1
3
1000
50
0
False
True
False
True
False
True


In [ ]:
s ="hello"
print(s)
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l','(ell)'))
print(' world '.strip())

hello
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [ ]:
# find sign of x
x = input("Enter x: ")
print("value of x:", x)
print(type(x))

# convert string x to int x
x = int(x)

# check sign
if x > 0:
    print("x is positive")
elif x < 0:
    print("x is negative")
else:
    print("x is zero")


value of x: 23
<class 'str'>
x is positive


# Python basics : Loops
### For-loop:
### While-loop:

In [ ]:
#iterating range
for x in range (0,10) :
    print("5 *",x,"=", x*5)
# iterating sequance
for x in "something":
    print(x)
# loop as long as x<5000
# loop count depends on startvalue of x
x =5
while x< 5000:
    print(x)
    x+=5

5 * 0 = 0
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
s
o
m
e
t
h
i
n
g
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995
1000
1005
1010
1015
1020
1025
1030
1035
1040
1045
1050
1055
1060
1065
1070
1075
1080
1085
1090
109

In [ ]:
x =10
y=3

print(x!=y and x<y)
print(x!=y or x<y)
print(not (x<y))

False
True
True


In [ ]:
# sequance of Hailstone 
# if n is 1 then the sequance ends
# if n is even then the next n of the sequance = n/2
# if n is odd then the next n of the sequance =(3+ n) +1

n = int(input("Enter a number: "))
print("n is ", n)

while not (n==1):              # same as n!=1
    if (n%2 == 0):
        n/=2
    else:
        n =(3*n)+1
    print(n)

n is  5
16
8.0
4.0
2.0
1.0


In [1]:
def sign(x):
    if x>0:
        return "positive"
    elif x<0:
        return "negative"
    else:
        return "zero"
    
x = int(input("Enter a number: "))
print(x, "is", sign(x))

for x in range(-5,5):
   print(x,"is", sign(x))

3 is positive
-5 is negative
-4 is negative
-3 is negative
-2 is negative
-1 is negative
0 is zero
1 is positive
2 is positive
3 is positive
4 is positive


In [8]:

list = [3, 1, 2]
print(list,list[2])
list[2] = "foo"
list.append("bar")
print(list)
x = list.pop()
print(x,list)
list = list + [8.3, False]
print(list)
print(list[-1])

[3, 1, 2] 2
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']
[3, 1, 'foo', 8.3, False]
False


In [9]:
for x in list:
    print(x)

nrs = range(0,5)
squares = [x ** 2 for x in nrs]
print (squares)

3
1
foo
8.3
False
[0, 1, 4, 9, 16]


In [11]:
print("foo" in list)
print("foo" not in list)
print("bar" in list)

if False in list:
    print(True)

True
False
False
True


In [12]:
list_of_list = [[1,2,3], [4,5,6],[7,8,9]]
for list in list_of_list:
    for x in list:
        print(x, end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [17]:
tuple = ("spring" ,"summer","autumn", "winter")
print(tuple)

set = {"apple", "banana", "cherry"}
set.add("mango")
set.add("apple")
print(set)

dictionary ={
    "a" : "apple",
    "b" : "banana",
    "c" : "cherry",
    "c" : "citron"
}
print(dictionary)
dictionary["y"] ="cherry"
print(dictionary)

('spring', 'summer', 'autumn', 'winter')
{'banana', 'cherry', 'apple', 'mango'}
{'a': 'apple', 'b': 'banana', 'c': 'citron'}
{'a': 'apple', 'b': 'banana', 'c': 'citron', 'y': 'cherry'}


In [20]:
import numpy as np # import library

lsit = [1,2,3,4,5]
print(lsit)
array =np.array([1,2,3,4,5])
print(array)

print(list*2) # look at the different!
print(array*2) # same at the different result!

print(np.arange(10))
print(np.zeros((10,)))
print(np.ones((2,3)))
print(np.full((5,),4))
print(np.eye(4))
print(np.random.random((1,4)))
print(np.random.random_integers(-10,10 , (4,4)))




[1, 2, 3, 4, 5]
[1 2 3 4 5]
[7, 8, 9, 7, 8, 9]
[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[4 4 4 4 4]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.65232627 0.70339109 0.91058838 0.52498608]]
[[ -4 -10  10  -5]
 [ -8  -8  -1  -9]
 [ -9  10   6  -1]
 [  5   4  -8  -9]]


C:\Users\MOHAMMAD MIRAZ\AppData\Local\Temp\ipykernel_2360\1254072400.py:17: DeprecationWarning: This function is deprecated. Please call randint(-10, 10 + 1) instead
  print(np.random.random_integers(-10,10 , (4,4)))


In [28]:
array = np.array([1,2,3,4,5,6,7,8])
print(array)
print(type(array))
print(array.dtype)
new_array =array.astype('f')
print(new_array)

print("SHAPE: "+ str(array.shape)+ " DIM: "+ str(array.ndim))

array_2D =np.reshape(array, (4,2))
print(array_2D)
print("SHAPE: " +str(array_2D.shape)+ " DIM: "+str(array_2D.ndim))

array_3D = np.reshape(array, (2,2,2))
print(array_3D)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5. 6. 7. 8.]
SHAPE: (8,) DIM: 1
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
SHAPE: (4, 2) DIM: 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
a = np.arange(8)**3 # exponent 3 --> 0^3 1^3 2^3 3^3 ....
print(a)
print(a[2:5])
print(a[:4])
print(a[4:])
a[::3] =-1
print(a)
print(a[::-1]) # reverse
print(a[1::2]) # odd indexes

[  0   1   8  27  64 125 216 343]
[ 8 27 64]
[ 0  1  8 27]
[ 64 125 216 343]
[ -1   1   8  -1  64 125  -1 343]
[343  -1 125  64  -1   8   1  -1]
[  1  -1 125 343]


In [38]:
a = np.arange(0,10)
b = np.arange(9,-1,-1)
print(a)
print(b)
c = a-b
print(c)
print(c<0)
print(np.where(c<0))
c %= 3 
print(c)
print(np.add(a,c))

#if condition == true,a+1, else  a 
print(np.where(a%2==1,a+1,a))

b =np.reshape(b,(2,5))
print(b)
print(b.sum(axis =0)) # sum of each column
print(b.min(axis=1)) # min of each row 
print(b.cumsum(axis =1)) # cumulative sum along each row
print(np.sqrt(b))



[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ True  True  True  True  True False False False False False]
(array([0, 1, 2, 3, 4], dtype=int64),)
[0 2 1 0 2 1 0 2 1 0]
[0 3 3 3 6 6 6 9 9 9]
[ 0  2  2  4  4  6  6  8  8 10]
[[9 8 7 6 5]
 [4 3 2 1 0]]
[13 11  9  7  5]
[5 0]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]
[[3.         2.82842712 2.64575131 2.44948974 2.23606798]
 [2.         1.73205081 1.41421356 1.         0.        ]]


### Pythonic 

In [41]:
data = ["apple","banana","mango","kiwi"]

# Simple looping of list
for val in data:
    print(val)

# Looping with index
for i, val in enumerate(data):
    print(i, val)

# Looping reverse list
for val in reversed(data):
    print(val)

apple
banana
mango
kiwi
0 apple
1 banana
2 mango
3 kiwi
kiwi
mango
banana
apple


In [43]:
data = ["apple","banana","mango","kiwi"]
colors = ["green", "yellow","orange", "green"]

# Create a dictionary of pairs
dc = dict(zip(data, colors))


# Loop dictionary
for key, val in dc.items():
    print(key, val)



apple green
banana yellow
mango orange
kiwi green


In [1]:
longest = ""
for word in wordlist:
    if word == word[::-1] and len(word) > len(longest):
        longest = word
print(longest)
max([word for word in wordlist if word == word[::-1]], key=len)


NameError: name 'wordlist' is not defined